###user registration
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"Vishal",
    "lastName":"L",
    "email":"vishal.user@gmail.com",
    "password":"Vishal"
}


###author registration
POST  http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"Rohit",
    "lastName":"R",
    "email":"Rohit.author@gmail.com",
    "password":"RohitR"
}

###user login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"anurag.user@gmail.com",
    "password":"Anurag"
}

###author login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"Rohit.author@gmail.com",
    "password":"RohitR"
}

###creating an article
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"698ca6a3ec3c6f9d04d6248d",
    "title":"test article2",
    "category":"trial2",
    "content":"trial content 2 created by rohit"
}

###read the articles by author
GET http://localhost:4000/author-api/articles/698ca6a3ec3c6f9d04d6248d

###updating an article
PUT  http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"698ca6a3ec3c6f9d04d6248d",
    "articleId":"698ca700ec3c6f9d04d62495",
    "title":"test article",
    "category":"trial",
    "content":"trial content is present in this"
}

###soft delete
DELETE http://localhost:4000/author-api/articles/698ca700ec3c6f9d04d62495/author/698ca6a3ec3c6f9d04d6248d

###logout
GET  http://localhost:4000/common-api/logout

###read the articles by user
GET http://localhost:4000/user-api/articles/698ca681ec3c6f9d04d62489

###adding a comment by the user
PUT  http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "userId":"698ca681ec3c6f9d04d62489",
    "articleId":"698ca712ec3c6f9d04d62499",
    "comments":"good article but needs more data"
}

###test res
GET   http://localhost:4000/test

###test res
GET   http://localhost:4000/hello

###admin login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"adminadmin"
}

###read the articles by admin
GET http://localhost:4000/admin-api/articles/698ca849ec77f16b9dc2616a

###blocking a user
PUT http://localhost:4000/admin-api/block/69898eb90b8f8095df2be3c1

###unblocking a blocked user
PUT http://localhost:4000/admin-api/unblock/69898eb90b8f8095df2be3c1

###change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"anurag.user@gmail.com",
    "password":"anurag",
    "newPassword":"Anurag"
}